# keys are stored in consul for INT, PREPROD and PRODUCTION platforms

# Kafka producer conf
spring:
  kafka:
    bootstrap-servers: ${ANALYTICS_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
